### ISSUE TITLE
CRASH, Cyanide Axolotl resource location invalid

### ISSUE THREAD

**Issue by EthanRStokes** [AkashiiKun/MoreAxolotlVariantsMod-Common#14]
Using MAVM 1.2.0 and MAVAPI 1.0.1 for 1.19.2

```java
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1568) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1316) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.11.jar:?]
Caused by: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: textures/entity/axolotl/axolotl_mavm:cyanide.png
	at net.minecraft.class_2960.<init>(class_2960.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_5774.handler$ikf000$getTexture(class_5774.java:1537) ~[client-intermediary.jar:?]
	at net.minecraft.class_5774.method_33306(class_5774.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_5774.method_3931(class_5774.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.redirect$fdn000$etf$alterTexture(class_922.java:3617) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_24302(class_922.java:155) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_927.method_4072(class_927.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_927.method_3936(class_927.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:141) ~[client-intermediary.jar:?]
	... 11 more

**Comment by AkashiiKun** [comment]
Cannot reproduce. Maybe you're using another mod that modifies axolotls too?

**Comment by EthanRStokes** [comment]
The only other mod I am using that adds axolotls is I believe `More Axolotls`

**Comment by AkashiiKun** [comment]
Yea, they're incompatible as my mod changes the axolotl entity renderer to get the new variant textures from a custom namespace instead of the vanilla namespace.

https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common/blob/4551e5c8c4871dece7db8caab07f06f015e29f58/Common/src/main/java/io/github/akashiikun/mavapi/v1/impl/mixin/AxolotlEntityRendererMixin.java#L49
