### ISSUE TITLE
Game Crashes when a Axolotl variant from MAVM mod spawns

### ISSUE THREAD

**Issue by quotabat** [AkashiiKun/MoreAxolotlVariantsMod-Common#20]
net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: textures/entity/axolotl/axolotl_mavm:black.png

[crash-2023-02-22_03.17.38-client.txt](https://github.com/AkashiiKun/MoreAxolotlVariantsMod-Common/files/10801977/crash-2023-02-22_03.17.38-client.txt)

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-02-22 03:17:38
Description: Rendering entity in world

net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: textures/entity/axolotl/axolotl_mavm:red.png
	at net.minecraft.class_2960.<init>(class_2960.java:38)
	at net.minecraft.class_2960.<init>(class_2960.java:46)
	at net.minecraft.class_5774.handler$fio000$getTexture(class_5774.java:1537)
	at net.minecraft.class_5774.method_33306(class_5774.java)
	at net.minecraft.class_5774.method_3931(class_5774.java:13)
	at net.minecraft.class_922.method_24302(class_922.java:155)
	at net.minecraft.class_922.method_4054(class_922.java:136)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2960.<init>(class_2960.java:38)
	at net.minecraft.class_2960.<init>(class_2960.java:46)
	at net.minecraft.class_5774.handler$fio000$getTexture(class_5774.java:1537)
	at net.minecraft.class_5774.method_33306(class_5774.java)
	at net.minecraft.class_5774.method_3931(class_5774.java:13)
	at net.minecraft.class_922.method_24302(class_922.java:155)
	at net.minecraft.class_922.method_4054(class_922.java:136)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Entity being rendered --
Details:
	Entity Type: minecraft:axolotl (net.minecraft.class_5762)
	Entity ID: 337786
	Entity Name: Axolotl
	Entity's Exact location: 72.50, 80.00, 205.50
	Entity's Block location: World: (72,80,205), Section: (at 8,0,13 in 4,5,12; chunk contains blocks 64,-64,192 to 79,319,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_5774@104c834
	Location: -0.92,-1.62,2.13 - World: (-1,-2,2), Section: (at 15,14,2 in -1,-1,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Rotation: -39.375
	Delta: 0.2199842
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by quotabat** [comment]
Tested by using axolotl spawn egg and it spawned normal vanilla variants
 without issue and when a MAVM spawns it crashes game. Does not crash server.

**Comment by quotabat** [comment]
![image](https://user-images.githubusercontent.com/118788463/220577229-fe08e960-184f-4d8f-915b-d0cdb6d4a189.png)

**Comment by quotabat** [comment]
Modpack used 
![image](https://user-images.githubusercontent.com/118788463/220577307-0bcbc03c-5738-40f1-a883-b60925765943.png)

**Comment by AkashiiKun** [comment]
Incompatibility with More Axolotls. They have to make a fix to work with my mod.
